apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: student-management
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: student-management-system-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres123@database:5432/studentdb"
          readinessProbe:
            httpGet:
              path: /students
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /students
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
