apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: student-management
  labels:
    app: database
type: Opaque
# Values are base64-encoded
# To encode: echo -n "value" | base64
# postgres     -> cG9zdGdyZXM=
# postgres123  -> cG9zdGdyZXMxMjM=
# studentdb    -> c3R1ZGVudGRi
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=
  POSTGRES_DB: c3R1ZGVudGRi
